### ISSUE TITLE
Прекоммит

### ISSUE THREAD

**Issue by nixel2007** [SmokyAce/integration-1c-redmine#1]
Добрый день. 
Случайно нарвался на ваш репозиторий. Судя по коммитам у вас есть проблемы с настройкой precommit1c. 
Я могу чем-нибудь помочь? 

P. S. Один из авторов os-версии precommit1c :)

**Comment by andranik-ss** [comment]
Добрый день,

Да есть такое дело))
Почему то, не срабатывает разбор файла .epf при фиксации.

Лог если честно не сильно информативный, а сам скрипт еще не успел хорошо
посмотреть.
Если запускаю отдельно
oscript v8files-extractor.os --decompile ...
То все отрабатывает на ура.

Если подскажете на что обратить внимание, буду признателен ))

28 марта 2016 г., 9:07 пользователь Nikita Gryzlov <notifications@github.com

> написал:
> 
> Добрый день.
> Случайно нарвался на ваш репозиторий. Судя по коммитам у вас есть проблемы
> с настройкой precommit1c.
> Я могу чем-нибудь помочь?
> 
> P. S. Один из авторов os-версии precommit1c :)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/SmokyAce/integration-1c-redmine/issues/1

## 

Best regards, Andranik Simonyan

_andranik.s.s@gmail.com andranik.s.s@gmail.com_
_cell: +38 (063) 457-07-71_

**Comment by nixel2007** [comment]
@SmokyAce Как устанавливали? Какие файлы и каталоги копировали в hooks? Вывод лога можете дать?

**Comment by andranik-ss** [comment]
Склонировал репозитарий xDrivenDevelopment/precommit1c - ветку develop
Скопировал указанные в README файлы в папку hooks своего проекта.
и выполнил команду "git config --local core.quotepath false"  в локальном репо проекта.

[v8files-extractor.cmdline.log.txt](https://github.com/SmokyAce/integration-1c-redmine/files/191549/v8files-extractor.cmdline.log.txt)
[v8files-extractor.log.txt](https://github.com/SmokyAce/integration-1c-redmine/files/191548/v8files-extractor.log.txt)

**Comment by nixel2007** [comment]
Хм. Лог v8files-extractor подозрительно пустой.

На всякий случай уточню:
1) Файлы скопировали в .git/hooks или просто в hooks в самом проекте?
2) Версия oscript? (`oscript -v`). Если < 1.0.12, рекомендую обновиться.
3) Есть какой-то лог в окне самого гита? Консольного или из sourcetree?

**Comment by andranik-ss** [comment]
1) Да, структура каталога .git/hooks как в README проекта precommit1c
2) 1Script Execution Engine. Version 1.0.13.77
3) Где смотреть лог не совсем понятно, если в каталоге проекта .git/log, то там ничего нет кроме
например:
Andranik Simonyan andranik.s.s@gmail.com 1459160241 +0300 commit: Тест прекоммита 

Может визуально Вы что то усмотрите ?
https://dl.dropboxusercontent.com/u/48615906/precommit-test.mp4

**Comment by nixel2007** [comment]
Кхм. у меня окно так быстро не закрывается :)
Можете успеть поставить галку "Показать полный вывод"?

**Comment by andranik-ss** [comment]
не успеваю ))) Есть еще какие то варианты получить такой лог ?

**Comment by andranik-ss** [comment]
В настройках SourceTree есть такой флажок ))

git -c diff.mnemonicprefix=false -c core.quotepath=false commit -q -F F:\Users\ASimonyan\AppData\Local\Temp\33kpoymk.vui
Start hooks before commit for v8unpack erf and epf

ИНФОРМАЦИЯ - precommit1c v2.0.0

ОТЛАДКА - Добавляю позиционный параметр ПутьВходящихДанных
ОТЛАДКА - Добавляю позиционный параметр ВыходнойКаталог
ОТЛАДКА - Добавляю позиционный параметр ВыходнойКаталог
ОТЛАДКА - Добавляю параметр-флаг --remove-orig-bin-files
ОТЛАДКА - Добавляю позиционный параметр ПутьВходящихДанных
ОТЛАДКА - Добавляю позиционный параметр ВыходнойКаталог
ОТЛАДКА - Добавляю параметр-флаг --recursive
ОТЛАДКА - Разбор команды: --git-precommit
ОТЛАДКА - Попадаю в РазобратьАргументы
ОТЛАДКА - Сбрасываю параметр-флаг: --remove-orig-bin-files
ОТЛАДКА - Выбран токен: src
ОТЛАДКА - Ищу именованный параметр src
ОТЛАДКА - Ищу параметр-флаг src
ОТЛАДКА - Установлено значение позиционного параметра <ВыходнойКаталог = src>
ОТЛАДКА - Выбран токен: 
ОТЛАДКА - Закончились токены
ОТЛАДКА - Трассировка РезультатРазбора:
ОТЛАДКА -        --remove-orig-bin-files:Нет
ОТЛАДКА -        ВыходнойКаталог:src
ОТЛАДКА - Трассировка РезультатКоманды.ЗначенияПараметров:
ОТЛАДКА -        --remove-orig-bin-files:Нет
ОТЛАДКА -        ВыходнойКаталог:src
Успешно выполнено.

**Comment by nixel2007** [comment]
Раскомментируйте строку 134 в файле v8files-extractor.os и попробуйте еще раз. Будет выведет отладочный лог самого прекоммита.
Сразу вопрос с порога - в папке v8reader есть что-нибудь?

**Comment by andranik-ss** [comment]
[коммит.txt](https://github.com/SmokyAce/integration-1c-redmine/files/191685/default.txt)

![1](https://cloud.githubusercontent.com/assets/15950153/14076736/43c8c4f6-f4ed-11e5-9180-115144089c11.JPG)

Вот результат ...

**Comment by nixel2007** [comment]
ё-моё, как же я это пропустил...

Добавьте в 795 строку:
`ОбработанныйПуть = Путь;`

Постараемся оперативно выпустить баг-фикс релиз.

**Comment by andranik-ss** [comment]
Да теперь все в порядке)))

**Comment by nixel2007** [comment]
Выпущен баг-фикс релиз 2.0.1. Содержание там такое же :)
Большое спасибо за отлов бага :)

**Comment by andranik-ss** [comment]
А Вам за своевременную помощь ... кто знает сколько бы я проковырялся))

**Comment by nixel2007** [comment]
@SmokyAce по поводу незафиксированных изменений и --remove-orig-bin-files.
Для его "красивой" работы нужно саму epf добавлять в `.gitignore`. Но тогда проблематично с ним работать через тот же sourcetree, т.к. надо файл надо добавлять принудительно, через `git add -f file.epf`

Так, мысли вслух.
У себя на работе использую такой подход, но имею это неудобство :)

**Comment by andranik-ss** [comment]
Спасибо за подсказку как раз по этой же причине полез изучать команды и возможности gita.

**Comment by andranik-ss** [comment]
Добрый день. Вы случайно не используете связку GitHub c Redmine? 

Меня интересует 
1. получение изменений Рэдмайном при очередном коммите;
2. добавление инфо о коммите в задачу.

Первое решается через настройку плагина - https://github.com/koppen/redmine_github_hook и Settings - Webhooks (GitHub), но не получается настроить обновление задачи (добавление коммита)
Второе решается с помощью настройки сервиса Settings - Services - Redmine (GitHub), но не отрабатывает получение изменений (sys/fetch_changesets)

Не подскажете есть какие то решения ?

**Comment by nixel2007** [comment]
Не работал с redmine в таком ключе, не смогу подсказать. На тренинге ребята из silverbulleters говорили, что оно настраивается и показывается, но без подробностей.
