### ISSUE TITLE
Управляемые формы?

### ISSUE THREAD

**Issue by AndreyLihomanov** [SmokyAce/integration-1c-redmine#3]
Доброгой день!
Подскажите внешняя обработка будет реализована на управляемых формах?

**Comment by denegny** [comment]
#2 

> Я так понимаю Вы имеете ввиду управляемое приложение 1С (в тонком клиенте). Да в планах есть но приступить получиться не раньше ноября.

**Comment by andranik-ss** [comment]
Добрый день. 
Да уже начал работу над ними. 
Какой функционал интересен в первую очередь ?

**Comment by AndreyLihomanov** [comment]
Добрый день!
Подскажите у меня лезут ошибки при нажатии кнопкb->запросы

Запрос вида: GET к ресурсу: /time_entries.json, с параметрами: &issue_id=535 не выполнен. Код состояния: 403
Результат ответа сервера неопределен

**Comment by AndreyLihomanov** [comment]
Еще бывает выскакивает ошибка "Поле объекта не обнаружено (user)" при открытии задачи

{ВнешняяОбработка.асИнтеграцияССистемамойУправленияПроектамиRedmine.Форма.Форма.Форма(1202)}: Поле объекта не обнаружено (user)
         СписокИсполнителей.Добавить(Структура.user.name);

**Comment by andranik-ss** [comment]
1.  По поводу ошибки 403 - Похоже что у вас нет доступа к "просмотру трудозатрат" в разделе "учет времени" в настройках Redmine.
2.  По поводу  ошибки "Поле объекта не обнаружено (user)" - Похоже что у вас не добавлены "Участники" в настройках проекта (Redmine). Попробуйте добавить... 

За внимание к обработке и за ошибки спасибо, обработка исключений на оные будет добавлена  в следующей версии. В будущем просьба открывать на каждую ошибку отдельную задачу на GitHub.

**Comment by AndreyLihomanov** [comment]
По поводу ошибки 403 - Похоже что у вас нет доступа к "просмотру трудозатрат" в разделе "учет времени" в настройках Redmine.

У меня полный доступ ко всем проектам и задачам, права администратора

По поводу ошибки "Поле объекта не обнаружено (user)" - Похоже что у вас не добавлены "Участники" в настройках проекта (Redmine). Попробуйте добавить... 

Участники добавлены во все проекты
